name: Build Flutter for Windows

on:
  push:
    branches: [ main ]
    tags:
      - 'prod-*'
      - 'dev-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter (Release)
        run: flutter build windows --release

      - name: Install Inno Setup
        run: |
          $innoSetupUrl = "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
          $innoSetupInstaller = "innosetup-installer.exe"
          Invoke-WebRequest -Uri $innoSetupUrl -OutFile $innoSetupInstaller
          Start-Process -FilePath $innoSetupInstaller -ArgumentList "/SILENT", "/NOCANCEL", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
          $innoPath = "${env:ProgramFiles(x86)}\Inno Setup 6"
          echo "$innoPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Download VC++ (prod only)
        if: startsWith(github.ref, 'refs/tags/prod-')
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "installer/vc_redist.x64.exe"

      - name: Use prod config
        if: startsWith(github.ref, 'refs/tags/prod-')
        run: |
          Copy-Item "installer/windows_installer_prod.iss" "installer/windows_installer.iss" -Force

      - name: Use dev config
        if: startsWith(github.ref, 'refs/tags/dev-')
        run: |
          Copy-Item "installer/windows_installer_dev.iss" "installer/windows_installer.iss" -Force

      - name: Create Installer
        run: |
          iscc.exe "installer/windows_installer.iss"

      - name: Upload Prod Installer
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: actions/upload-artifact@v4
        with:
          name: shop-manager-installer-prod-x64
          path: installer/Output/shop_manager_setup_x64.exe

      - name: Upload Dev Installer
        if: startsWith(github.ref, 'refs/tags/dev-')
        uses: actions/upload-artifact@v4
        with:
          name: shop-manager-installer-dev-x64
          path: installer/Output/shop_manager_setup.exe